SET INPUT_definitionIsInCurrentTeamProject=false
SET INPUT_tfsServer=https://benjsawesometfstest.visualstudio.com/DefaultCollection/
SET INPUT_teamProject=Build Test
SET INPUT_ignoreSslCertificateErrors=false
SET INPUT_waitForQueuedBuildsToFinishRefreshTime=10
SET INPUT_failTaskIfBuildsNotSuccessful=true
SET INPUT_cancelBuildsIfAnyFails=true
SET INPUT_treatPartiallySucceededBuildAsSuccessful=true
SET INPUT_downloadBuildArtifacts=true
SET INPUT_dropDirectory=D:\Temp\Whatever
SET INPUT_clearVariable=true
SET INPUT_authenticationMethod=Personal Access Token
SET INPUT_username=
SET INPUT_password=sww3otrtvfaqi4sqcqqjceq23lxgvlyjfoftqox7272qc3vxyi2q

SET TriggeredBuildIds=2286,2189

node index.js