SET INPUT_definitionIsInCurrentTeamProject=false
SET INPUT_tfsServer=https://benjsawesometfstest.visualstudio.com/DefaultCollection/GitTest
SET INPUT_buildDefinition=TestBuildToTrigger
SET INPUT_queueBuildForUserThatTriggeredBuild=false
SET INPUT_useSameSourceVersion=false
SET INPUT_useSameBranch=false
SET INPUT_branchToUse=
SET INPUT_waitForQueuedBuildsToFinish=fals
SET INPUT_waitForQueuedBuildsToFinishRefreshTime=10
SET INPUT_failTaskIfBuildsNotSuccessful=false
SET INPUT_downloadBuildArtifacts=false
SET INPUT_dropDirectory=
SET INPUT_storeInEnvironmentVariable=true
SET INPUT_demands=
SET INPUT_buildParameters=
SET INPUT_ignoreSslCertificateErrors=false
SET INPUT_authenticationMethod=Personal Access Token
SET INPUT_username=
SET INPUT_password=sww3otrtvfaqi4sqcqqjceq23lxgvlyjfoftqox7272qc3vxyi2q
SET INPUT_enableBuildInQueueCondition=false
SET INPUT_includeCurrentBuildDefinition=false
SET INPUT_blockingBuildsList=
SET INPUT_dependentOnSuccessfulBuildCondition=false
SET INPUT_dependentBuildsList=
SET INPUT_dependentOnFailedBuildCondition=false
SET INPUT_dependentFailingBuildsList=



node index.js