"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TeamFoundationCollectionUri = "SYSTEM_TEAMFOUNDATIONCOLLECTIONURI";
exports.TeamProject = "SYSTEM_TEAMPROJECT";
exports.RequestedForUsername = "BUILD_REQUESTEDFOR";
exports.RequestedForUserId = "BUILD_REQUESTEDFORID";
exports.SourceVersion = "BUILD_SOURCEVERSION";
exports.SourceBranch = "BUILD_SOURCEBRANCH";
exports.CurrentBuildDefinition = "BUILD_DEFINITIONNAME";
exports.OAuthAccessToken = "SYSTEM_ACCESSTOKEN";
exports.RepositoryType = "BUILD_REPOSITORY_PROVIDER";
exports.TfsRepositoryType = "TfsVersionControl";
exports.ApiUrl = "_apis";
exports.AuthenticationMethodDefaultCredentials = "Default Credentials";
exports.AuthenticationMethodOAuthToken = "OAuth Token";
exports.AuthenticationMethodBasicAuthentication = "Basic Authentication";
exports.AuthenticationMethodPersonalAccessToken = "Personal Access Token";
exports.BuildStateNotStarted = "notStarted";
exports.BuildStateInProgress = "inProgress";
exports.BuildStateCompleted = "completed";
exports.BuildResultSucceeded = "succeeded";
